spring:
  application:
    name: giselle-piercing-api

  main:
    banner-mode: "off"

  datasource:
    url: jdbc:postgresql://localhost:5432/giselle_piercing_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: 0285douglas@gmail.com
    password: yzoxlmgpqflyvnae
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

mercado-pago:
  access-token: TEST-7009698705827422-052211-cf7c9a3675e60569cf3c18d907a700de-169782701

security:
  user:
    name: "dev"
    password: "dev"

logging:
  exception-conversion-word: "%wEx{5}"
  level:
    org.springframework.web: ERROR
    org.apache.catalina: ERROR
    org.hibernate: ERROR